Bookstore: styling
kinginthenorthcodez/bookstore pull request #5
Opened 2022-06-12 04:39 UTC by kinginthenorthcodez

## Bookstore: styling

### NOTE:  Progress bar pending due to dependencies problems, will fix asap though would like to ask if can please overlook this part. I am trying to work on my last tasks for submission 👍🏽 

- Apply React best practices and language style guides in code.

Warm Regards
@kinginthenorthcodez

2022-06-12 06:02 UTC, kinginthenorthcodez commented
@AmaduKamara would you please help with a review on this PR 👍🏽

2022-06-16 18:47 UTC, elyor-doniyorov requested changes
Hi @kinginthenorthcodez, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✅ There are no linter errors
✅ Descriptive PR title and description


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 18:47 UTC, elyor-doniyorov commented on src/index.css
>  * {
- [x] Please make sure that Styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/)Styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/). Take a look at the screenshots of your app and original design below and try to make yours similar to the one in Zeplin 👇 
- Yours 👇 
![Screenshot (269)](https://user-images.githubusercontent.com/67087664/174141340-c5f8df3f-5287-4612-a12d-77cd4803100c.png)
1.  In the created books section :  
                                                      1) Capitalize first letters of `comments , remove, edit `and `completed `words;
                                                      2) Make `Update Progress` text color light grey
3. In the Add New Book section: 
                                                     1)Write `Add Book` instead of `Submit`  and it should be in the same row with other inputs
                                                     2) Remove background color
  - Original 👇 
  
![originale](https://user-images.githubusercontent.com/67087664/174143253-c3966fe6-e234-4eca-9e71-e327454a336d.png)

2022-06-16 20:33 UTC, kinginthenorthcodez commented on src/index.css
>  * {
@elyor-doniyorov . Required Changes made as per code review suggestion 👍🏽

![image](https://user-images.githubusercontent.com/94127418/174158208-e54c4804-4aff-4d7b-b280-7e5bcbbea5c7.png)
 

#### Note: Please note that there is no background color on the add-book section. Earlier that was the default body color of the white background from the browser. 👍🏽

2022-06-16 20:50 UTC, Lucas-Masaba approved these changes
# Hello @kinginthenorthcodez  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Design is looking similar to that if the zeplin template 👍 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 21:03 UTC, kinginthenorthcodez commented
@Lucas-Masaba Thanks for the review 👍🏽

2022-06-16 21:03 UTC, merged

2022-06-16 21:03 UTC, kinginthenorthcodez commented
Merged #5  into development